### ISSUE TITLE
Adapter Tchap web(urls en config.json) pour Tchap web RIE

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#1013]
https://github.com/tchapgouv/tchap-infra/issues/2705#issuecomment-2134899972

```[tasklist]
### Tasks
- [ ] plan minimal de test
- [x] https://github.com/tchapgouv/tchap-web-v4/pull/1022
- [ ] https://github.com/tchapgouv/tchap-web-v4/pull/1033
```
