### ISSUE TITLE
Upgrade element 1.11.72

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#1059]
[1.11.70](https://github.com/element-hq/element-web/releases/tag/v1.11.70)
- Remove outdated iframe sandbox attribute (https://github.com/matrix-org/matrix-react-sdk/pull/12633)
- Fix stray background colour on markdown body (https://github.com/matrix-org/matrix-react-sdk/pull/12628)
- Add SSO redirect option for login page (https://github.com/element-hq/element-web/pull/27576)

## Retrocompatibily issue with Firefox esr versions 
- Polyfill Intl.Segmenter
- Or revert commit that introduce it in element 
```[tasklist]
### Tasks
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1080
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1081
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1077
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1083
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1096
```

**Comment by MarcWadai** [comment]
- Le commit introduisant la régression côté element : https://github.com/matrix-org/matrix-react-sdk/pull/12617
- Cependant, il faudra aussi voir si le simple revert de la pr marche car `compound-web` utilise aussi l'api Segmenter.

**Comment by MarcWadai** [comment]
Polyfill made by element https://github.com/element-hq/element-web/pull/27803
