### ISSUE TITLE
déployer Element call à partir du live kit, dans un premier temps sur Tchap web

### ISSUE THREAD

**Issue by julie-ri** [tchapgouv/tchap-web-v4#1087]
```[tasklist]
### Tasks
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1117
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1128
- [x] Affichage des boutton (rejoindre, créer un call) https://github.com/tchapgouv/tchap-web-v4/pull/1127
- [x] Modification de la config https://github.com/tchapgouv/tchap-web-v4/pull/1127
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1130
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1215
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1231
```

**Comment by MarcWadai** [comment]
Pour activer cette fonctionnalité, plusieurs choses doivent être activés dans la config : 

```
    "setting_defaults": {
        ...
        "UIFeature.widgets": true,
        ...
    },
        "features": {
         ...
        "feature_group_calls": true  // car c'est toujours en lab
    },
        "element_call": {
        "url": "https://element-call.tchap.incubateur.net/"
    }
```

Il est nécessaire d'activer la fonctionnalité des Widgets afin de pouvoir utiliser element call. Cela engendre quelques modifications UI qu'il faudrait cacher selon moi : 

- Un nouveau paramètre dans les settings de sécurité 
![image](https://github.com/user-attachments/assets/e1bde6af-57db-4d4b-92ec-c1604580306a)

- Une nouvelle tab dans les information d'un salon 
![Screenshot_20241007_181558](https://github.com/user-attachments/assets/a0de52cd-4106-454a-b430-4dff67ef5603)

**Comment by MarcWadai** [comment]
@julie-ri @Delphgateau Quels types de salon seront autorisé à passer des appels de groupe ? Tous ou simplement les salons privés ?

Il est aussi possible de paramétrer dans le salon les droits des personnes pouvant démarrer ou rejoindre un appel
![image](https://github.com/user-attachments/assets/2e9a28d0-dc9b-4d52-abcb-91fafb8f5ec1)

**Comment by Delphgateau** [comment]
Tous les salons privés (fermés ou ouverts aux externes). Sur les forums ça me semble pas adapté.
Sur les futurs salons non chiffrés privés, à voir aussi car le but est d'inviter un max de monde.

**Comment by julie-ri** [comment]
il faut aussi qu'on voit car il y a une limite du nb de users dans un call, il faudrait le spécifier sur le bouton call ou à la création d'un salon ?

**Comment by Delphgateau** [comment]
Yes, quelle est la limite ? 
Je pense qu'il vaut mieux mettre l'indication sur le bouton call qu'à la création du salon. Sinon l'info sera perdue et vue que par le créateur.
"Cet appel est limité à X participants"

**Comment by julie-ri** [comment]
pour le moment on est sur 10 participants (en 2024) et element va travailler à augmenter ce seuil en 2025

**Comment by MarcWadai** [comment]
Peut être implémenter un système qui permet de griser le bouton si le nombre de personne dans le salon > seuil. 

Dans ce cas là, la notion de salon privée, public, privée non chiffré... est moins importante je trouve (sachant que les admins peuvent en plus configurer à leurs guises les autorisations pour démarrer et rejoindre un appel).

**Comment by julie-ri** [comment]
les calls seront chiffrés de bout en bout -> est-ce que c'est compatible avec forum où les gens n'ont pas de clés de chiffrement ?

**Comment by MarcWadai** [comment]
@julie-ri je pense qu'il n'y a pas de soucis. Element ne fait pas de distinction non plus et j'ai testé dans un salon public ca marche aussi. Il doit pouvoir créer les clés à la volée (à confirmer).

**Comment by julie-ri** [comment]
faire les travaux sur le livekit de la suite.

**Comment by MarcWadai** [comment]
déployé en lab : beta interne avec l'element call de prod (https://call.tchap.gouv.fr) https://github.com/tchapgouv/tchap-web-v4/pull/1327
