### ISSUE TITLE
Upgrade element - Merge Matrix-react-sdk into element

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#1152]
## Description
Cette prochaine mis à jour ramène toute la partie matrix-react-sdk dans element.
- La PR de merge sur element [Pull Request #28213](https://github.com/element-hq/element-web/pull/28213/commits)
- Le commit de la muerte qui intègre la plupart des fichiers https://github.com/element-hq/element-web/pull/28213/commits/f0ee7f7905e447b47b26b579435024a2238822dd

## TODO

Il faudra : 
- [x] Reporter tout les patchs Tchap
- [x] Vérifier que les customisations marchent toujours
- [x] Mettre à jour le script de check pour les traductions
- [x] Mettre à jour les autres scripts de build
- [x] Mettre à jour le workflow git si besoin
- [x] Supprimer le système de subtree
- [x] modifier les scripts d’installations
