### ISSUE TITLE
Améliorer l'UX/ l'ensemble des messages d'erreur lié aux externes 

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#1164]
```[tasklist]
### Tasks
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1145
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1144
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/1076
```
