### ISSUE TITLE
Settings : Authorize access to external from a private room

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#169]
In the Room Settings , Security and Privacy, we would like to add the feature to allow the access to external users from a private room for the administrator

Before: 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/3725676/190169003-ae63cb58-cf5b-403f-8047-d1aa1578cf66.png">

After :
<img width="486" alt="image" src="https://user-images.githubusercontent.com/3725676/190208072-f4a2ea80-598d-4278-ad3c-d54bd3952bda.png">
- When clicking on the toggle : 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/3725676/190208278-79847fc7-feb6-46f3-9a0f-fa684d114f7b.png">

### Dev notes
- this feature is using the following synapse module : https://github.com/vector-im/synapse-room-access-rules
- code from matrix-react-js for this feature(when changing this particular setup) : https://github.com/tchapgouv/matrix-react-sdk/commit/1bdada20ef7fcd701c338984bda4d5aba20d76ea#diff-9f226359a8fc92d20a9572db5ad4ad640dbc337b2e96d25f163ae988ecf43b20
- code from matrix-react-js for this feature(when creating a room) : https://github.com/tchapgouv/matrix-react-sdk/commit/f22ec41d4982ba95bf4e1c711bf5268bb397b85d

### Task to perform to resolve this ticket : 
- [x] display the toggle switch 
- [x] perform api call to backend in order to allow the access to externals
- [x] add the following guards when allowing the access to externals : 
  - [x] role = administrator of the room
  - [x] room state = private
  - [x] accessRule = restricted
- [x] add a popup window to confirm if we want to change the access to externals
  - Title of the popup : Allow the externals to join this room
  - Description of the popup : This action is irreversible. Are you sure you want to allow the externals to join this room ?
- [ ] Add a description/information/label on the room `Room opened to external users` if the room is opened to external users
- [x] perform api call to backend when creating a private room opened to external users
- [ ] we cannot leave a room that is opened to external : is that normal?
- [x] add e2e tests
