### ISSUE TITLE
Terminer upgrade element 1.11.39

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#618]
https://github.com/vector-im/element-web/compare/v1.11.30...v1.11.39
https://github.com/matrix-org/matrix-react-sdk/compare/v3.71.1...v3.78.0
https://github.com/matrix-org/matrix-js-sdk/compare/v25.0.0...v27.2.0

Good things : 
- [ ] https://github.com/vector-im/element-web/commit/6e8f76e93c6d92156a0d7e5c9c675b946148df02
- [ ] https://github.com/vector-im/element-web/commit/2bcfb257ea79e9ff4c45807c103e5dd27b69b28b
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11273
- [x] Fixes for [CVE-2023-37259](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=CVE-2023-37259) / [GHSA-c9vx-2g7w-rp65](https://github.com/matrix-org/matrix-react-sdk/security/advisories/GHSA-c9vx-2g7w-rp65)

Bad smells : 
- [x] https://github.com/vector-im/element-web/pull/25736
- [x] la liste des sessions a été migré vers un panel dédiée. nous devons choisir : garder l'ancienne vue que nous avions personnalisée (avec une customisation) et cacher le nouveau panel qui liste les devices/sessions OU personnaliser le nouveau panel (et mettre à jour notre doc) OU garder les deux?

```[tasklist]
### Tasks
- [x] clean patches code to ease rebase
- [ ] study rebase opportunities and risks
- [ ] proceed rebase
- [x] is logo on Welcome page broken ?
- [x] node upgraded to 18. Do we want 19 ? Does it break anything ?
- [x] RoomHeader has changed is now LegacyRoomHeader. Check that TchapExternalRoomHeader still works (should display "External users allowed")
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/670
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/669
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/687
- [x] fix broken tests
```

**Comment by estellecomment** [comment]
Customisations deprecation moved to new ticket : https://github.com/tchapgouv/tchap-web-v4/issues/646

**Comment by odelcroi** [comment]
fixes : https://github.com/tchapgouv/tchap-web-v4/issues/290
