### ISSUE TITLE
Upgrade to element-web 1.11.44

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#734]
Diffs : 
element-web : https://github.com/vector-im/element-web/compare/v1.11.39...v1.11.44
react-sdk : 3.78.0->3.81.0 : https://github.com/matrix-org/matrix-react-sdk/compare/v3.78.0...v3.81.0
js-sdk : 27.2.0->28.2.0 : https://github.com/matrix-org/matrix-js-sdk/compare/v27.2.0...v28.2.0

**Comment by estellecomment** [comment]
Notable things in [element-web changelog](https://github.com/vector-im/element-web/compare/v1.11.39...v1.11.44#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed) : 

1.11.40 : https://github.com/tchapgouv/tchap-web-v4/pull/735
- [x] Disable 3pid fields in settings when `m.3pid_changes` capability is disabled ([\#11430](https://github.com/matrix-org/matrix-react-sdk/pull/11430)). Fixes #25995. Contributed by @kerryarchibald.
Could this help us, since we don't allow change of 3pid (email) ?
- [x] Polish & delabs `Exploring public spaces` feature ([\#11423](https://github.com/matrix-org/matrix-react-sdk/pull/11423)).
New feature out of labs : do we want it ? (it's already there, nobody 
- [x] Simplify registration with email validation ([\#11398](https://github.com/matrix-org/matrix-react-sdk/pull/11398)). Fixes #25832 #23601 and #22297.
Breaks registration patch ? (fixed) Helpful for us ? (yes, notified bizdev of change)

1.11.41 :
- [x] Deprecate customisations in favour of Module API ([\#25736](https://github.com/vector-im/element-web/pull/25736)). Fixes #25733.
Are our customisations broken ? 
-> not yet :)
- [x] Render custom images in reactions according to MSC4027 ([\#11087](https://github.com/matrix-org/matrix-react-sdk/pull/11087)). Contributed by @sumnerevans.
Custom emojis in labs !!!!! 🥳 
-> nothing to see yet, even with labs enabled. Wait a bit more...
- [x] Room header UI updates ([\#11507](https://github.com/matrix-org/matrix-react-sdk/pull/11507)). Fixes #25892.
Possibly breaks our patches for displaying "ouvert aux externes" in room header. We're still on the LegacyRoomHeader, we could move to RoomHeader.

1.11.42 : Nothing. (small bugfix version)

1.11.43 : Nothing. (element desktop changes only)

1.11.44 : Nothing notable.


Work on OIDC in several PRs.

**Comment by estellecomment** [comment]
First part done ! We're at 1.11.40.

For 1.11.44 :
https://github.com/vector-im/element-web/compare/v1.11.40...v1.11.44
https://github.com/matrix-org/matrix-react-sdk/compare/v3.79.0...v3.81.0
https://github.com/matrix-org/matrix-js-sdk/compare/v28.0.0...v28.2.0

**Comment by estellecomment** [comment]
- [ ] translations : key format has changed, so many translations are broken in our customisations files.
