### ISSUE TITLE
activer la géolocalisation

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#930]
#### What would you like to do?
- partager sa position

#### How would you like to achieve it?

- tested as moderateur, and as no-rights user, it seems to work. Not restricted to admins.

```[tasklist]
### Tasks
- [ ] https://github.com/tchapgouv/tchap-web-v4/issues/981
- [ ] https://github.com/tchapgouv/tchap-web-v4/pull/1007
- [ ] https://github.com/tchapgouv/tchap-infra/pull/2767
```

**Comment by estellecomment** [comment]
PR experimentale : https://github.com/tchapgouv/tchap-web-v4/pull/932

**Comment by estellecomment** [comment]
Quand la feature n'est pas activée sur le client, il ne peut pas non plus visualiser la location que qqn d'autre à envoyé. Ca fait un peu crade. On n'a que : 
```
Unable to load map: This homeserver is not configured to display maps.
Shared their location: User Location geo:48.XXX,2.XXX;u=40 at 2024-03-11T12:56:28.654Z
```

**Comment by MarcWadai** [comment]
Je suis d'accord le contenu du fallback fait peur.  Peut-être juste mettre la première phrase ? Les infos de geoloc en plus ne sert pas a grand chose imo.
J'ai checker le code et ce contenu est facilement changeable (le composant `LocationBodyFallbackContent`).
