### ISSUE TITLE
Study : Unit test on tchap components ?

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#937]
#### What would you like to do?
 - Unit tests components that have been modified by Tchap
 - integration tests : catch regressions. Are the outputs and inputs of our components still matching element's expectations ?
 
#### Why would you like to do it?
Make sure that the changes are not broken/that there is no regression after every update

#### How would you like to achieve it?
- We need to prioritize the different components that have been impacted first, it can be sorted by features (taken from `patches.json`
```
    "tchap-room-icons"
    "simplify-exchange-key-message"
    "bug-reporting"
    "content-scanner"
    "forgot-password"
    "hide-room-alias-settings"
    "login"
    "registration-for-mainlining"
    "password-policy"
    "public-room-server-list"
    "auto-accept-tac"
    "hide-discovery-email-phone-settings"
    "activate-expired-account-panel"
    "cross-signing-ui"
    "fix-inviting-a-person-already-present-in-the-room"
    "activate-cross-signing-and-secure-storage-react"
    "user-menu"
    "ux-improvements-for-xsss"
    "use-the-term-direct-messages-not-people"
    "remove-thread-buttons"
    "change-sections-order-in-security-privacy-settings"
    "add-translations-for-server-errors"
    "error-tchap-is-down"
    "export-room-members"
    "tchap-features-from-config"
    "only-fr-and-en"
    "better-text-for-locked-messages"
    "customize-room-header-bar"
    "display-call-button-anyway"
 ```
- Check on matrix-react-sdk and try to import the existing test of the component.
- Modify the test to adapt with Tchap code

### TODO
 - [ ] Modify PULL REQUEST template file to add some info
 - [ ] Remove all enzymes tests
 - [ ] Write proper guideline for patches and customisations tests

**Comment by estellecomment** [comment]
Add also to the study 
 - customisations
 - tchap "normal" code
 - which patches/customisations/components should be tested first ? which are the most likely to break and contain the most important features ?

**Comment by MarcWadai** [comment]
- Le but principale est de savoir si notre composant n’a pas de régression après un rebase, tout les calls api etc seront donc mocker.
- Savoir si le composants de base a changer ses props entrante et ses données sortante
    - une modification de nom, une suppression, UI etc
- Un composant n’est pas nécessairement seul, il peut être composé de multiple autre composants. Cependant, dans le tests nous voulons vraiment tester le comportement générale des input et output, il peut donc suffire de simplement tester les props entrante et le résultat de sortie de ceux là
- Nous avons besoin de comparer deux types de composants :
    - la base étant soit un composant element, soit un composant du sdk react
    - notre composant tchap

Nous avons 3 types de modifications dans le code:

- customisations
- patches
- Code normal

### Config

- testing-library a été ajouté
- 2 alias dans tsconfig et jestconfig ont été ajouté, on peut maintenant écrire :
    - `~/tchap-web` → chemin vers la racine du projet
    - `~/tchap-web-dep` → chemin vers le dossier yarn-linked-dependencies

### Patches

- Comparer avec le test original pour voir s’il y a des choses intéressante qui peuvent être récupérées. La plupart du temps non 🤪
- Nos patches sont souvent des changements UI donc pour être sur qu’elles n’ont pas bouger, nous pouvons simplement utiliser un test de snapshot.
    - ce test snapshot peut capturer des changements visuels utilisé par les composants, mais pas en ce qui concerne la logique et les props
- Faire un test sur les props d’entrées de votre composant
    - identifier les composants du sdk que vous utilisez
- Faire un test sur le résultat de sortie de votre composant (ca peut aussi tout simplement correspondre au snapshot)
- Ensuite pour vous pouvez ajouter de la logique spécifique à Tchap

### Customisations
TBD

### Code normal
Juste des tests normaux 😆

**Comment by MarcWadai** [comment]
De base les tests unitaires utilise enzyme une librairie pour aider a écrire des tests pour react. Depuis, matrix-react-sdk, utilise testing-library avec jest. Je suppose que c'est parcequ'enzyme nécessitait une migration importante pour passer à la version supérieur et rester compatible avec les versions récente de React.

Il va falloir un clean des anciens tests écrient avec enzyme et les mettre à jour, pour pouvoir l’enlever complètement de notre stack.

**Comment by estellecomment** [comment]
@MarcWadai il reste des trucs à faire sur ce ticket ? Si oui faire des petites checkbox, si non fermer le ticket ?

**Comment by MarcWadai** [comment]
@estellecomment  Oui je pense que pour le moment on peut la close. Quand j'aurais plus de recule je pourrais compléter les guidelines et pourquoi pas créer une commande gui génère un template de test
